trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - script: npm install
        displayName: 'Install npm dependencies'

      - script: npm install
        displayName: 'Build the Node.js application'

      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          containerRegistry: 'Docker-Hub-Connection'  # Replace with your Docker Hub service connection name
          repository: 'shivakrishna99/AZ-NodeJS-App'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: |
            latest
            $(Build.BuildId)
