trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies and build'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'Docker-Hub-Connection' # Replace with the name of your Docker service connection
    repository: 'shivakrishna99/az-nodejs-app' # Replace with the name of your Docker image repository
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      latest
